---
- name: Install metric beat
  hosts: webservers
  become: true
  tasks:
    # Curl command module to download metricbeat
  - name: Download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.15.0-amd64.deb

    # Install command module installs metricbeat
  - name: install metricbeat
    command: dpkg -i metricbeat-7.15.0-amd64.deb

    # Copy module copies metricbeat config file to /etc/ansible
  - name: drop in metricbeat config
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

    # Enables and configures docker module for metribeat
  - name: enable and configure docker module for metric beat
    command: metricbeat modules enable docker

    # Sets up metricbeat
  - name: setup metric beat
    command: metricbeat setup

    # Starts metricbeat service
  - name: start metric beat
    command: service metricbeat start